"""Tests for Algorithm 7.4: ROI Calculator for Optimization.

TDD RED phase -- these tests are written BEFORE the implementation exists.
They will fail with ImportError until
src/algorithms/algorithm_7_4_roi_calculator.py is implemented.

Specification: Requirements/08-Algorithm-Review-Summary.md
(Algorithm 7.4: ROI Calculator, Phase 2, Medium complexity).

Algorithm 7.4 calculates the Return on Investment from optimization
recommendations generated by other algorithms, providing business justification
for license changes:
  - Accept a set of optimization recommendations (from algorithms 2.2, 4.2, etc.)
  - Calculate total implementation cost (labor hours, risk mitigation)
  - Calculate total savings (monthly, annual, multi-year)
  - Calculate ROI metrics: payback period, NPV, IRR, ROI percentage
  - Account for confidence levels (discount low-confidence recommendations)
  - Support configurable discount rate for NPV calculation
  - Categorize recommendations by risk tier (safe, moderate, high-risk)
  - Generate executive summary suitable for business cases

Key behaviors:
  - Simple ROI: (savings - cost) / cost * 100
  - Payback period: implementation_cost / monthly_savings (in months)
  - Confidence-adjusted savings: savings * confidence_score
  - NPV: sum of discounted future cash flows minus implementation cost
  - High-confidence recs: full savings in calculation
  - Low-confidence recs: discounted savings
  - Zero recommendations: ROI of 0, no errors
  - Multi-year projection (1, 3, 5 year horizons)
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from src.algorithms.algorithm_7_4_roi_calculator import (
    OptimizationRecommendationInput,
    ROIAnalysis,
    ROISummary,
    calculate_roi,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PRICING_PATH: Path = Path(__file__).parents[2] / "data" / "config" / "pricing.json"
MONETARY_TOLERANCE: float = 0.01
PERCENTAGE_TOLERANCE: float = 0.1

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_pricing() -> dict[str, Any]:
    """Load the pricing configuration JSON."""
    with open(PRICING_PATH, "r", encoding="utf-8") as fh:
        return json.load(fh)


def _build_recommendations(
    recs: list[dict[str, Any]],
) -> list[OptimizationRecommendationInput]:
    """Build a list of optimization recommendation inputs.

    Args:
        recs: List of dicts with keys:
            recommendation_id, algorithm_id, user_id,
            monthly_savings, confidence_score (0.0-1.0),
            implementation_hours (labor hours for this change),
            risk_tier (safe/moderate/high-risk).
    """
    inputs = []
    for rec in recs:
        inputs.append(
            OptimizationRecommendationInput(
                recommendation_id=rec.get("recommendation_id", "REC-001"),
                algorithm_id=rec.get("algorithm_id", "2.2"),
                user_id=rec.get("user_id", "USR-001"),
                monthly_savings=rec.get("monthly_savings", 120.0),
                confidence_score=rec.get("confidence_score", 0.95),
                implementation_hours=rec.get("implementation_hours", 0.5),
                risk_tier=rec.get("risk_tier", "safe"),
            )
        )
    return inputs


# ---------------------------------------------------------------------------
# Test: Simple ROI Calculation
# ---------------------------------------------------------------------------


class TestSimpleROICalculation:
    """Test scenario: Single high-confidence recommendation.

    Monthly savings: $120 (downgrade from Finance to TM)
    Implementation cost: 0.5 hours * $100/hour = $50
    Annual savings: $1,440
    ROI: ($1,440 - $50) / $50 * 100 = 2780%
    """

    def test_roi_percentage_correct(self) -> None:
        """ROI should be (annual_savings - cost) / cost * 100."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "recommendation_id": "REC-001",
                    "monthly_savings": 120.0,
                    "confidence_score": 0.95,
                    "implementation_hours": 0.5,
                }
            ]
        )

        # -- Act --
        result: ROIAnalysis = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        assert result.roi_percentage > 0
        assert result.total_annual_savings > 0

    def test_payback_period_months(self) -> None:
        """Payback period = implementation_cost / monthly_savings."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "monthly_savings": 120.0,
                    "confidence_score": 1.0,
                    "implementation_hours": 1.0,
                }
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=120.0,  # impl cost = $120
        )

        # -- Assert --
        # Payback: $120 / $120 per month = 1.0 months
        assert abs(result.payback_period_months - 1.0) < 0.1


# ---------------------------------------------------------------------------
# Test: Confidence-Adjusted Savings
# ---------------------------------------------------------------------------


class TestConfidenceAdjustedSavings:
    """Test scenario: Recommendations with varying confidence levels.

    High confidence (0.95): savings mostly preserved.
    Low confidence (0.55): savings significantly discounted.
    """

    def test_confidence_adjustment_applied(self) -> None:
        """Low-confidence recommendations should have discounted savings."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "recommendation_id": "REC-HIGH",
                    "monthly_savings": 100.0,
                    "confidence_score": 0.95,
                    "implementation_hours": 0.5,
                },
                {
                    "recommendation_id": "REC-LOW",
                    "monthly_savings": 100.0,
                    "confidence_score": 0.55,
                    "implementation_hours": 0.5,
                },
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        # Confidence-adjusted annual savings should be less than raw
        raw_annual = 200.0 * 12  # $2,400
        assert result.confidence_adjusted_annual_savings < raw_annual
        assert result.confidence_adjusted_annual_savings > 0

    def test_raw_vs_adjusted_savings_different(self) -> None:
        """Raw and confidence-adjusted savings should differ."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "monthly_savings": 100.0,
                    "confidence_score": 0.60,
                    "implementation_hours": 0.5,
                }
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        assert result.confidence_adjusted_annual_savings < result.total_annual_savings


# ---------------------------------------------------------------------------
# Test: Multiple Recommendations Aggregated
# ---------------------------------------------------------------------------


class TestMultipleRecommendationsAggregated:
    """Test scenario: 10 recommendations aggregated into single ROI."""

    def test_total_savings_is_sum(self) -> None:
        """Total savings should be sum of all recommendation savings."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "recommendation_id": f"REC-{i:03d}",
                    "monthly_savings": 50.0,
                    "confidence_score": 0.90,
                    "implementation_hours": 0.25,
                }
                for i in range(10)
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        expected_monthly = 50.0 * 10
        expected_annual = expected_monthly * 12
        assert abs(result.total_monthly_savings - expected_monthly) < MONETARY_TOLERANCE
        assert abs(result.total_annual_savings - expected_annual) < MONETARY_TOLERANCE

    def test_implementation_cost_is_sum(self) -> None:
        """Total implementation cost = sum of hours * hourly rate."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "recommendation_id": f"REC-{i:03d}",
                    "monthly_savings": 50.0,
                    "confidence_score": 0.90,
                    "implementation_hours": 0.5,
                }
                for i in range(10)
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        expected_cost = 10 * 0.5 * 100.0  # $500
        assert abs(result.total_implementation_cost - expected_cost) < MONETARY_TOLERANCE


# ---------------------------------------------------------------------------
# Test: Multi-Year Projection
# ---------------------------------------------------------------------------


class TestMultiYearProjection:
    """Test scenario: 1-year, 3-year, and 5-year projections."""

    def test_multi_year_projections_present(self) -> None:
        """Result should include 1, 3, and 5-year savings projections."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "monthly_savings": 100.0,
                    "confidence_score": 0.90,
                    "implementation_hours": 1.0,
                }
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        assert result.year_1_savings > 0
        assert result.year_3_savings > result.year_1_savings
        assert result.year_5_savings > result.year_3_savings

    def test_5_year_savings_is_5x_annual(self) -> None:
        """5-year savings should approximately equal 5 * annual."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "monthly_savings": 100.0,
                    "confidence_score": 1.0,
                    "implementation_hours": 0.0,
                }
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        # Without discounting, 5-year = 5 * annual
        expected_5yr = result.total_annual_savings * 5
        # Allow tolerance for potential NPV discounting
        assert result.year_5_savings <= expected_5yr + MONETARY_TOLERANCE


# ---------------------------------------------------------------------------
# Test: Risk Tier Categorization
# ---------------------------------------------------------------------------


class TestRiskTierCategorization:
    """Test scenario: Recommendations categorized by risk tier."""

    def test_risk_tier_counts(self) -> None:
        """Result should count recommendations by risk tier."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {"recommendation_id": "S1", "risk_tier": "safe"},
                {"recommendation_id": "S2", "risk_tier": "safe"},
                {"recommendation_id": "M1", "risk_tier": "moderate"},
                {"recommendation_id": "H1", "risk_tier": "high-risk"},
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        assert result.safe_recommendations_count == 2
        assert result.moderate_recommendations_count == 1
        assert result.high_risk_recommendations_count == 1

    def test_safe_savings_vs_total(self) -> None:
        """Safe-tier savings should be reported separately."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "recommendation_id": "S1",
                    "risk_tier": "safe",
                    "monthly_savings": 100.0,
                    "confidence_score": 0.95,
                },
                {
                    "recommendation_id": "H1",
                    "risk_tier": "high-risk",
                    "monthly_savings": 200.0,
                    "confidence_score": 0.55,
                },
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        assert result.safe_tier_annual_savings > 0
        assert result.safe_tier_annual_savings < result.total_annual_savings


# ---------------------------------------------------------------------------
# Test: NPV Calculation
# ---------------------------------------------------------------------------


class TestNPVCalculation:
    """Test scenario: Net Present Value with configurable discount rate."""

    def test_npv_positive_for_good_recommendations(self) -> None:
        """Positive-savings recommendations should yield positive NPV."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "monthly_savings": 500.0,
                    "confidence_score": 0.90,
                    "implementation_hours": 2.0,
                }
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
            discount_rate=0.10,  # 10% annual discount
        )

        # -- Assert --
        assert result.npv > 0

    def test_higher_discount_rate_lower_npv(self) -> None:
        """Higher discount rate should yield lower NPV."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "monthly_savings": 200.0,
                    "confidence_score": 0.90,
                    "implementation_hours": 1.0,
                }
            ]
        )

        # -- Act --
        result_low_rate = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
            discount_rate=0.05,
        )
        result_high_rate = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
            discount_rate=0.20,
        )

        # -- Assert --
        assert result_low_rate.npv > result_high_rate.npv


# ---------------------------------------------------------------------------
# Test: Zero Recommendations
# ---------------------------------------------------------------------------


class TestZeroRecommendations:
    """Test scenario: No recommendations provided."""

    def test_zero_recommendations_zero_roi(self) -> None:
        """Zero recommendations should yield zero ROI."""
        # -- Arrange --
        recs: list[OptimizationRecommendationInput] = []

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        assert result.total_monthly_savings == 0
        assert result.total_annual_savings == 0
        assert result.total_implementation_cost == 0
        assert result.roi_percentage == 0


# ---------------------------------------------------------------------------
# Test: Executive Summary
# ---------------------------------------------------------------------------


class TestExecutiveSummary:
    """Test scenario: Result should include executive summary text."""

    def test_executive_summary_present(self) -> None:
        """ROI analysis should generate an executive summary."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "monthly_savings": 100.0,
                    "confidence_score": 0.90,
                    "implementation_hours": 0.5,
                }
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        assert result.executive_summary is not None
        assert len(result.executive_summary) > 20  # Non-trivial text

    def test_executive_summary_includes_savings(self) -> None:
        """Executive summary should mention savings figures."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "monthly_savings": 500.0,
                    "confidence_score": 0.95,
                    "implementation_hours": 1.0,
                }
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        # Summary should contain dollar amounts or savings references
        assert "$" in result.executive_summary or "savings" in result.executive_summary.lower()


# ---------------------------------------------------------------------------
# Test: Recommendation Count Summary
# ---------------------------------------------------------------------------


class TestRecommendationCountSummary:
    """Test scenario: Verify recommendation count tracking."""

    def test_total_recommendation_count(self) -> None:
        """Total recommendation count should match input."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {"recommendation_id": f"REC-{i}"} for i in range(7)
            ]
        )

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        assert result.total_recommendations == 7


# ---------------------------------------------------------------------------
# Test: Configurable Implementation Cost Rate
# ---------------------------------------------------------------------------


class TestConfigurableImplementationCost:
    """Test scenario: Different hourly rates affect total cost and ROI."""

    def test_higher_rate_lower_roi(self) -> None:
        """Higher implementation cost rate should lower ROI."""
        # -- Arrange --
        recs = _build_recommendations(
            [
                {
                    "monthly_savings": 100.0,
                    "confidence_score": 0.90,
                    "implementation_hours": 2.0,
                }
            ]
        )

        # -- Act --
        result_cheap = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=50.0,
        )
        result_expensive = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=200.0,
        )

        # -- Assert --
        assert result_cheap.roi_percentage > result_expensive.roi_percentage


# ---------------------------------------------------------------------------
# Test: Algorithm Metadata
# ---------------------------------------------------------------------------


class TestAlgorithmMetadata:
    """Test scenario: Verify algorithm_id is '7.4'."""

    def test_algorithm_id_is_7_4(self) -> None:
        """ROIAnalysis should carry algorithm_id '7.4'."""
        # -- Arrange --
        recs: list[OptimizationRecommendationInput] = []

        # -- Act --
        result = calculate_roi(
            recommendations=recs,
            hourly_implementation_cost=100.0,
        )

        # -- Assert --
        assert result.algorithm_id == "7.4"
